---
- hosts: machines
  tasks:
    - name: Create install directory on remote machines
      file:
        path: "{{ install_dir }}"
        state: directory
        owner: "{{ ansible_ssh_user }}"
        group: "{{ ansible_ssh_user }}"
        mode: 0755
      when: ansible_connection == "ssh"

    - name: Create temp directory on remote machines
      file:
        path: "{{ install_dir }}/tmp"
        state: directory
        owner: "{{ ansible_ssh_user }}"
        group: "{{ ansible_ssh_user }}"
        mode: 0755
      when: ansible_connection == "ssh"
