#for the moment, the dir_create.yml and dependencies.yml are being run from dependencies.sh
#- import_playbook: plays/dir_create.yml
#- import_playbook: plays/dependencies.yml
- import_playbook: plays/mysqldb.yml
- import_playbook: plays/gitlab.yml
- import_playbook: plays/lb.yml
- import_playbook: plays/ms.yml
- import_playbook: plays/executionnodes.yml
